language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: Z622DwKusxI7H+0NAGR/ztJWBbOgDtUwjUZ5Rc36mBwJlG1FYvHERzGobbTw4voZ/kI0A1+pGBF2//MqUZUMrtKjo1xjdPIruGYcW3D+TvtHqwJQ/DKapHA+NrqO5e+LITt+fDajU9HLJPLCF/kIHlB5J0F6VSOIYpMaR5k8mw41Gn+6P4jo01H1uiOmF/U24jsNS+q1gKNhqYC9rflPpSXM4cglMvUSUPFIqcwRcSyfWXx9ibVUFX3ajR7Rt9kUigcib3/f++jNOGdezWzkcQcLXAaj+RtYvM5NU7OYhtNXk7SVMlUaXkmDFl9snaco9dIisazR18lseItmg6ehYweNqIY03L/PGCPbMAaJjrwV85f016xvVdPzYOoPzgbzgvTYYJS5/7a2qF7CeyrjsBx41BKyqhTv0TfkETmqF8WQV9Dpcv6soCR9k4NNe3wZArlafoO+sPtzVo7Afp4eiglx/0VPUnG70OJcgqspzfbWs+uUQWrtC5NW8jxXQ+2ptVe49TOuNK6g4w/D7ZmcWB/fr4oYUjuBxXnAWv4TzJ62rHDEByNxoDX5J4pTdW8OW2yG2rOW2AMocChp9aCzWqkE+x9WmdpnmZ/HwA+/RaOcE3HcknZIZhscM9Y9iPnHKRctSz39OLPLlM5qZcHlHeM8zDlRw7I/ZAyyZ8BTXME=
  app: nassimreactboilerplate
  on:
    repo: na6im/react-boilerplate
